### ISSUE TITLE
Error: Could not load file or assembly Microsoft.Bcl.AsyncInterfaces

### ISSUE THREAD

**Issue by juanmpy** [rkrehn/YTAD#9]
Hello.

I just installed YTAD, and when I tried use it, I got this error message:

![image](https://github.com/user-attachments/assets/ab1af8f2-f4c3-44de-9b88-c80aba78b72f)

**************** Exception text **************
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
in YTPD.Form1.button1_Click(Object sender, EventArgs e)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine] (TStateMachine& stateMachine)
in YTPD.Form1.button1_Click(Sender Object, EventArgs e)
in System.Windows.Forms.Button.OnClick(EventArgs e)
in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
in System.Windows. Forms.Control.WmMouseUp(Message&m, Button MouseButtons, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message&m)
at System.Windows.Forms.ButtonBase.WndProc(Message&m)
at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by rkrehn** [comment]
Thanks for sharing. This is related to one of the reference files and I believe it's an installer issue. Let me dig into the solution.

**Comment by rkrehn** [comment]
Thanks for sharing. This is related to one of the reference files and I believe it's an installer issue. Let me dig into the solution.

**Comment by rkrehn** [comment]
Yup, that was the issue. Please download the latest release.
